# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/peneb/Desktop/git/dejarik/fpga_dejarik/fpga_dejarik.srcs/sources_1/bd/dejarik/ip/dejarik_dlmb_bram_if_cntlr_0/dejarik_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'dejarik_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/peneb/Desktop/git/dejarik/fpga_dejarik/fpga_dejarik.gen/sources_1/bd/dejarik/ip/dejarik_dlmb_bram_if_cntlr_0/dejarik_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dejarik_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/peneb/Desktop/git/dejarik/fpga_dejarik/fpga_dejarik.srcs/sources_1/bd/dejarik/ip/dejarik_dlmb_bram_if_cntlr_0/dejarik_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'dejarik_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/peneb/Desktop/git/dejarik/fpga_dejarik/fpga_dejarik.gen/sources_1/bd/dejarik/ip/dejarik_dlmb_bram_if_cntlr_0/dejarik_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dejarik_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
